import { writeFileSync } from 'node:fs';
import type { ListReport } from '../types/index.js';

/**
 * MarkdownReporter
 *
 * Exports repository list reports to Markdown format
 */
export class MarkdownReporter {
  /**
   * Save list report to Markdown file
   */
  saveToFile(report: ListReport, filename: string): void {
    const markdown = this.generateMarkdown(report);
    writeFileSync(filename, markdown, 'utf-8');
  }

  /**
   * Generate Markdown string from report
   */
  generateMarkdown(report: ListReport): string {
    const lines: string[] = [];

    // Title
    lines.push(`# Repository List Report: ${report.list}`);
    lines.push('');
    lines.push(`**Generated:** ${new Date(report.generated).toLocaleString()}`);
    lines.push('');

    // Summary
    lines.push('## Summary');
    lines.push('');
    lines.push(`- **Total Repositories:** ${report.summary.total_repos}`);
    lines.push(
      `- **Actions Enabled:** ${report.summary.actions_enabled}/${report.summary.total_repos} (${Math.round((report.summary.actions_enabled / report.summary.total_repos) * 100)}%)`
    );
    lines.push(
      `- **Security Enabled:** ${report.summary.security_enabled}/${report.summary.total_repos} (${Math.round((report.summary.security_enabled / report.summary.total_repos) * 100)}%)`
    );
    lines.push(`- **Total Issues:** ${report.summary.total_issues}`);
    lines.push(`- **Critical Issues:** ${report.summary.critical_issues}`);
    lines.push(`- **High Issues:** ${report.summary.high_issues}`);
    lines.push('');

    // Recommendations
    if (report.recommendations.length > 0) {
      lines.push('## Recommendations');
      lines.push('');
      for (const rec of report.recommendations) {
        lines.push(`- ${rec}`);
      }
      lines.push('');
    }

    // Repository table
    lines.push('## Repositories');
    lines.push('');
    lines.push('| Repository | Actions | Security | Issues | Status |');
    lines.push('|------------|---------|----------|--------|--------|');

    for (const repo of report.repositories) {
      const actionsIcon = repo.actions_enabled ? '✅' : '❌';
      const securityIcon = repo.security_enabled ? '✅' : '❌';
      const status =
        repo.security_issues === 0
          ? '🟢 Good'
          : repo.security_issues > 2
            ? '🔴 Issues'
            : '🟠 Review';

      lines.push(
        `| [${repo.full_name}](${repo.url}) | ${actionsIcon} | ${securityIcon} | ${repo.security_issues} | ${status} |`
      );
    }

    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('*Report generated by GitHub Security Analysis Tools*');

    return lines.join('\n');
  }
}
